# dockerhub: https://hub.docker.com/_/haproxy/

version: '3.8'

services:
  haproxy:
    image: haproxy:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:    
      - haproxy:/usr/local/etc/haproxy
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    user: root
    stdin_open: true
    tty: true

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  haproxy: